/*PROBLEM 1*/

--QUESTION 1
SELECT
    PERSON_ID,
    FIRST_NAME,
    PREFERRED_FIRST_NAME,
    LAST_NAME,
    DATE_OF_BIRTH,
    HIRE_DATE,
    OCCUPATION,
    
    CASE 
        WHEN PREFERRED_FIRST_NAME IS NOT NULL 
        THEN PREFERRED_FIRST_NAME ELSE FIRST_NAME 
    END AS REPORTING_NAME
    
FROM PERSON;

--QUESTION 2
SELECT *
FROM PERSON
WHERE OCCUPATION IS NULL;

--QUESTION 3
SELECT *
FROM PERSON
WHERE DATE_OF_BIRTH < TO_DATE('08/07/1990', 'MM/DD/YYYY');

--QUESTION 4
SELECT *
FROM PERSON
WHERE HIRE_DATE <= SYSDATE AND HIRE_DATE >= SYSDATE - 100;

--QUESTION 5
SELECT PERSON.* 
FROM PERSON
INNER JOIN ADDRESS
ON PERSON.PERSON_ID = ADDRESS.PERSON_ID
WHERE ADDRESS.ADDRESS_TYPE = 'HOME';

--QUESTION 6
SELECT DISTINCT PERSON.*, ADDRESS.ADDRESS_ID,
    CASE
        WHEN ADDRESS_ID IS NULL
        THEN 'NONE'
        ELSE ADDRESS_TYPE
    END AS ADDRESS_TYPE
FROM PERSON
LEFT JOIN ADDRESS
ON PERSON.PERSON_ID = ADDRESS.PERSON_ID AND ADDRESS.ADDRESS_TYPE = 'BILL';

--QUESTION 7
SELECT ADDRESS_TYPE, COUNT(ADDRESS_TYPE) AS COUNT 
FROM ADDRESS 
WHERE ADDRESS_TYPE = 'BILL' OR ADDRESS_TYPE = 'HOME' 
GROUP BY ADDRESS_TYPE;

--QUESTION 8
SELECT P.LAST_NAME,
    CASE
        WHEN A.ADDRESS_ID IS NULL
        THEN NULL
        ELSE A.STREET_LINE_1 || ', ' || A.CITY || ', ' || A.STATE || ' ' || A.ZIP_CODE
    END AS HOME_ADDRESS,
    
    CASE
        WHEN A2.ADDRESS_ID IS NULL
        THEN NULL
        ELSE A2.STREET_LINE_1 || ', ' || A2.CITY || ', ' || A2.STATE || ' ' || A2.ZIP_CODE
    END AS BILLING_ADDRESS    
FROM PERSON P
LEFT JOIN ADDRESS A
ON P.PERSON_ID = A.PERSON_ID AND A.ADDRESS_TYPE = 'HOME'
LEFT JOIN ADDRESS A2
ON P.PERSON_ID = A2.PERSON_ID AND A2.ADDRESS_TYPE = 'BILL'
ORDER BY P.PERSON_ID;

--QUESTION 9
UPDATE PERSON
SET OCCUPATION = 'X'
WHERE PERSON_ID
IN
    (SELECT PERSON_ID
    FROM ADDRESS
    WHERE ADDRESS.ADDRESS_TYPE = 'BILL');
COMMIT;